site_name: LingeBot manuál
site_url: https://RadekMocek.github.io/PDO/
theme:
  name: readthedocs
  prev_next_buttons_location: bottom
  sticky_navigation: false
  titles_only: true

markdown_extensions:
  - mdx_truly_sane_lists
  - admonition

extra_css: 
  - css.css

nav:
  - Rychlé odkazy: quicklinks.md
  - Úvod:
    - Obsah manuálu: index.md
    - Důležité pojmy: concepts.md
  - Jak začít:
    - Založení uživatelského účtu: 01JakZacit/0zalozeniuctu.md
    - Vytvoření serveru a uživatelské rozhraní: 01JakZacit/1zalozeniserveru.md
    - Přidání bota na server, zadávání příkazů: 01JakZacit/2pozvanibota.md
  - Dostupné funkce a jak je používat:
    - Seznam dostupných příkazů: 02HlavniInstance/0dostupneprikazy.md
    - /explain – Výklad teorie  : 02HlavniInstance/1explain.md
    - /generate – Generace příkladů: 02HlavniInstance/2generate.md
    - /render – Vykreslování matematiky: 02HlavniInstance/3render.md
    - /setup – Nastavení bota: 02HlavniInstance/4setup.md
  - Provoz vlastní instance:
    - Vytvoření aplikace na<br>Discord Developer Portal: 03ProvozVlastniInstance/h.md
    - První spuštění: 03ProvozVlastniInstance/h.md
    - Synchronizace příkazů: 03ProvozVlastniInstance/h.md
    - Seznam příkazů pro provozovatele: 03ProvozVlastniInstance/h.md
    - Spuštění v prostředí Docker: 03ProvozVlastniInstance/4docker.md
  - Přidání vlastního obsahu:
    - Popis projektu: 04VlastniObsah/h.md
    - Pravidla pro zápis MD souborů: 04VlastniObsah/h.md
    - Vlastní téma pro výklad teorie: 04VlastniObsah/h.md
    - Vlastní kategorie příkladů: 04VlastniObsah/h.md
