site_name: LingeBot manuál
site_url: https://RadekMocek.github.io/PDO/
theme: readthedocs
markdown_extensions:
  - mdx_truly_sane_lists
nav:
  - Úvod: index.md
  - Jak začít:
    - Představení platformy Discord: 01JakZacit/0predstaveni.md
    - Založení účtu: h.md
    - Vytvoření serveru a pozvání bota: h.md
  - Dostupné funkce a jak je používat:
    - h: h.md
  - Provoz vlastní instance:
    - h: h.md