site_name: LingeBot manuál
site_url: https://RadekMocek.github.io/PDO/
theme:
  name: readthedocs
  prev_next_buttons_location: bottom

markdown_extensions:
  - mdx_truly_sane_lists

nav:
  - Rychlé odkazy: quicklinks.md
  - Úvod:
    - Obsah manuálu: index.md
    - Důležité pojmy: concepts.md
  - Jak začít:
    - Představení platformy Discord: 01JakZacit/0predstaveni.md
    - Založení účtu: h.md
    - Vytvoření serveru: h.md
    - Pozvání bota na server: h.md
  - Dostupné funkce a jak je používat:
    - Seznam dostupných příkazů: h.md
    - /explain – Výklad teorie  : h.md
    - /generate – Generace příkladů: h.md
    - /render – Vykreslování matematiky: h.md
    - /setup – Možnosti moderace: h.md
  - Provoz vlastní instance:
    - Vytvoření aplikace na Discord Developer Portal: h.md
    - První spuštění: h.md
    - Synchronizace příkazů: h.md
    - Seznam příkazů pro majitele: h.md
    - Spuštění v prostředí Docker: 03ProvozVlastniInstance/4docker.md
  - Přidání vlastního obsahu:
    - Popis projektu: h.md
    - Pravidla pro zápis MD souborů: h.md
    - Vlastní téma pro výklad teorie: h.md
    - Vlastní kategorie příkladů: h.md