site_name: LingeBot manuál
site_url: https://RadekMocek.github.io/PDO/
theme:
  name: readthedocs
  prev_next_buttons_location: bottom
  sticky_navigation: false
  titles_only: true

markdown_extensions:
  - mdx_truly_sane_lists
  - admonition

extra_css: 
  - css.css

nav:
  - Úvod:
    - Rychlé odkazy: quicklinks.md
    - Obsah manuálu: index.md
    - Důležité pojmy: concepts.md
  - Jak začít:
    - Založení uživatelského účtu: 01JakZacit/0zalozeniuctu.md
    - Vytvoření serveru a jeho uživatelské rozhraní: 01JakZacit/1zalozeniserveru.md
    - Přidání bota na server a odesílání příkazů: 01JakZacit/2pozvanibota.md
  - Dostupné funkce a jak je používat:
    - Seznam dostupných příkazů: 02HlavniInstance/0dostupneprikazy.md
    - /explain – Výklad teorie  : 02HlavniInstance/1explain.md
    - /generate – Generace příkladů: 02HlavniInstance/2generate.md
    - /render – Vykreslování matematiky: 02HlavniInstance/3render.md
    - /setup – Nastavení bota: 02HlavniInstance/4setup.md
  - Provoz vlastní instance:
    - Vytvoření aplikace na Discord Developer Portal: 03ProvozVlastniInstance/0vytvoreniaplikacenaddp.md
    - Stažení zdrojových kódů a první spuštění: 03ProvozVlastniInstance/1prvnispusteni.md
    - Synchronizace příkazů: 03ProvozVlastniInstance/2slashsync.md
    - Spuštění v prostředí Docker: 03ProvozVlastniInstance/3docker.md
  - Přidání vlastního obsahu:
    - Struktura projektu: 04VlastniObsah/0popisprojektu.md
    - Pravidla pro zápis Markdown souborů: 04VlastniObsah/1markdownpravidla.md
    - Vlastní téma pro výklad teorie: 04VlastniObsah/2vlastniteorie.md
    - Vlastní kategorie příkladů: 04VlastniObsah/3vlastnipriklady.md
